dns-records/hopic-data-donnes-phac-aspc-gc-ca.yaml

Add record set for `hopic-sdpac.data-donnes.phac-aspc.gc.ca`.

Add HoPiC DNS delegation

---

dns-records/geocoder-alpha-phac-gc-ca.yaml

Added a dns entry for pelias geocoder

Added DNS record set for pelias geocoder

---

.github/workflows/validdate-domain.yaml

* Update validdate-domain.yaml

Update validdate-domain.yaml (#18)

---

dns-records/data-readiness-repository-data-phac-gc-ca.yaml

Added new dns record for data readiness repository  - not yet ready for review as we need to update the record set.

Added Data Readiness Respository record

---

.github/workflows/validdate-domain.yaml

resolve an issue where sentiment scoring was too sensitive.

updated sentiment

---

dns-records/leandhis2-alpha-phac-gc-ca.yaml

Please approve the Request 1 and merge.
Sending the pull request with the refactored file

Request 2 to add lean-dhis2 dns

---

infra-deployment-scripts/zone-info.json

Putting managed zones in a json object for future use.

Putting managed zones in a json object for future use. 

---

.github/workflows/validdate-domain.yaml

there was an edge case where the script tried to scan for files that have been deleted. 
The script has been updated to resolve this case

Fix script

---

dns-records/backstage-alpha-phac-aspc-gc-ca.yaml

Add record set for the [sci-portal](https://github.com/PHACDataHub/sci-portal) project.

Add backstage record set

---

infra-deployment-scripts/create-dns-zones.sh

Refactored create-dns-zones.sh

---

.github/workflows/validate-zone.yaml
dns-records/atip-dlp-alpha-phac-gc-ca.yaml
dns-records/backstage-alpha-phac-aspc-gc-ca.yaml
dns-records/data-readiness-repository-data-phac-gc-ca.yaml
dns-records/dhis2-beta-phac-aspc-gc-ca.yaml
dns-records/geocoder-alpha-phac-gc-ca.yaml
dns-records/hopic-data-donnes-phac-aspc-gc-ca.yaml
dns-records/leandhis2-alpha-phac-gc-ca.yaml
dns-records/llm-alpha-phac-gc-ca.yaml
dns-records/shiny-alpha-phac-aspc-gc-ca.yaml

Add known project IDs

---

root-sync.yaml
zones/alpha-aspc-gc-ca.yaml
zones/alpha-phac-aspc-gc-ca.yaml
zones/alpha-phac-gc-ca.yaml
zones/api-ipa-phac-aspc-gc-ca.yaml
zones/api-phac-gc-ca.yaml
zones/beta-aspc-gc-ca.yaml
zones/beta-phac-aspc-gc-ca.yaml
zones/data-donnees-phac-aspc-gc-ca.yaml
zones/data-phac-gc-ca.yaml
zones/donnees-aspc-gc-ca.yaml
zones/ipa-aspc-gc-ca.yaml
zones/open-ouvert-phac-aspc-gc-ca.yaml
zones/open-phac-gc-ca.yaml
zones/ouvert-aspc-gc-ca.yaml

- Add root-sync for zones dir
- Fix zone manifests by adding namespace
Relates to #59

feat: add root-sync for zones dir

---

README.md
dns-records/jitaccess-alpha-phac-aspc-gc-ca.yaml

- Changed metadata.annotations.codeSourceRepository to metadata.annotations.sourceCodeRepository in readme
- Updated jitaccess DNS record to reflect sourceCodeRepository field name change

Fixed typo in readme

---

dns-records/catalogue-alpha-phac-aspc-gc-ca.yaml

Add entry for the data-catalog
Note that, 
- This project is on not on the PHAC GCP, but on SSC's experimentation space
- This project is already in production under `phac-aspc.alpha.canada.ca`

add catalog DNS record

---

README.md
dns-records/atip-dlp-alpha-phac-gc-ca.yaml
dns-records/backstage-alpha-phac-aspc-gc-ca.yaml
dns-records/catalogue-alpha-phac-aspc-gc-ca.yaml
dns-records/data-readiness-repository-data-phac-gc-ca.yaml
dns-records/dhis2-beta-phac-aspc-gc-ca.yaml
dns-records/entreessecurisees-alpha-phac-aspc-gc-ca.yaml
dns-records/geocoder-alpha-phac-gc-ca.yaml
dns-records/hopic-data-donnes-phac-aspc-gc-ca.yaml
dns-records/hopic-data-phac-gc-ca.yaml
dns-records/infra-auth-alpha-phac-gc-ca.yaml
dns-records/jitaccess-alpha-phac-aspc-gc-ca.yaml
dns-records/ky-alpha-phac-gc-ca.yaml
dns-records/ky2.yaml
dns-records/leandhis2-alpha-phac-gc-ca.yaml
dns-records/llm-alpha-phac-gc-ca.yaml
dns-records/safeinputs-alpha-phac-aspc-gc-ca.yaml
dns-records/shiny-alpha-phac-aspc-gc-ca.yaml
dns-records/signals-signaux-alpha-phac-aspc-gc-ca.yaml

As per @tcaky 's request, some annotations were converted to labels. Additionally, the README has been updated to reflect these changes, ensuring that the new format is clearly documented.

Convert annotations to labels

---

dns-records/is-it-signed-alpha-phac-gc-ca.yaml

Replacing https://isitchristmas.com/ with is-it-signed.alpha.phac.gc.ca.

added record for is it signed 

---

dns-records/harbor-alpha-phac-gc-ca.yaml

Creating the record sets for harbor-alpha-phac-gc-ca

harbor-alpha-phac-gc-ca DNS record sets

---

dns-records/safeinputs-alpha-phac-aspc-gc-ca.yaml

Update for new safeinputs project space.
Relates to https://github.com/PHACDataHub/acm-core/pull/311.

feat: update safeinputs record set

---

dns-records/ippm-pigp-alpha-phac-aspc-gc-ca.yaml

DNS Entry for IPPM-PIGP-DNS

---

k8s/README.md

Add some documentation around infrastructure, cluster setup and maintenance.

feat: update k8s readme
